//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public string MaDH { get; set; }
        public System.DateTime NgayMua { get; set; }
        public string SDTKH { get; set; }
        public string DCGiaoHang { get; set; }
        public double TongTien { get; set; }
        public string DVT { get; set; }
        public double TienGiam { get; set; }
        public string TinhTrang { get; set; }
        public string TrangThaiDH { get; set; }
        public string tgGiaoHang { get; set; }
        public double PhiVanChuyen { get; set; }
        public string maKH { get; set; }
        public string maSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        public virtual ThongTinKH ThongTinKH { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
