//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.ThongTinKHs = new HashSet<ThongTinKH>();
        }
    
        public string maSP { get; set; }
        public string TinhTrangSP { get; set; }
        public string MauSac { get; set; }
        public int KichThuoc { get; set; }
        public string HinhAnh1 { get; set; }
        public string MoTaSP { get; set; }
        public double Gia { get; set; }
        public int SLBan { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string MaHang { get; set; }
        public string CatID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ThuongHieuSP ThuongHieuSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinKH> ThongTinKHs { get; set; }
    }
}
